"""Introduce installation_id

Revision ID: 505535721e47
Revises: 74143061b286
Create Date: 2023-02-08 13:47:52.518626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505535721e47'
down_revision = '74143061b286'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'configuration',
        sa.Column(
            'installation_id',
            sa.String(length=100),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration', 'installation_id')
    # ### end Alembic commands ###
